version: "3"
services:
    db:
      container_name: db
      image: mysql
      ports:
       - "3306:3306"  
      environment:
         - MYSQL_ROOT_PASSWORD=seniority
         - MYSQL_DATABASE=seniority

      volumes:
         - $PWD/mysql/data:/var/lib/mysql
         - $PWD/mysql/init:/docker-entrypoint-initdb.d/:ro
